name: GitHub Actions Demo
on: [push]
jobs:
  test command:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [ 16.x ]
    steps:
      - name: Check out repository code
        uses: actions/checkout@v3
      - name: Staring Node.js $ {{ matrix.node-version }}
        uses: actions/setup-node@v3
      - name: install-modules
        run: npm install
      - name: build project
        run: npm run build
      - name: run unit test
        run: npm run test
      - name: run e2e test
        run: npm run wdio




